#ifndef __DISPLAY_H__

#include "appdefs.h"

#define FILE_NAME_LENGTH 65

class TDisplayTask : public TTask
{
public:
  inline TDisplayTask (const char* name , const int stack_size , const int priority ) : TTask(name , stack_size , priority , false)
     {

     }

       typedef struct
       {
         uint8_t x ;
         uint8_t y ;
       } TPos ;

       typedef enum { dcWriteReg = 0 ,
                      dcClear ,
                      dcClear_str,
                      dcSymbolOut,
                      dcStringOut,
                      dcCurPos,
                      dcLed_Write,
		      dcSec_Print,
                      dcCount } TCommand ;

       typedef struct
                 {
                   uint8_t x;
                   uint8_t y;
                 } TCurPos;
       typedef struct
                 {
                   uint32_t data;
                 } TSec_PrintParam;
       typedef struct
                 {
	          uint8_t x;
                  uint8_t y;
                  uint8_t count ;
                 } TClear_strParams ;
       typedef struct
                 {
		  uint8_t x;
                  uint8_t y;
                  uint8_t string[FILE_NAME_LENGTH] ;
                 } TStringOutParams ;
       typedef struct
                 {
	          uint8_t x;
                  uint8_t y;
                  uint8_t symbol ;
                 } TSymbolOutParams ;
       typedef struct
       {
         TCommand cmd ;
         union
         {
           TClear_strParams Clear_strParams;
           TSymbolOutParams SymbolOutParams ;
           TStringOutParams StringOutParams ;
           TCurPos CurPos;
           TSec_PrintParam Sec_PrintParam;
         } ;
       }   TDisplayCmd ;

       // send command from code/tasks
       inline TQueue::TQueueSendResult Command( TDisplayCmd* cmd )
         {
     	     return queue->SendToBack(cmd,0);
      	 }

       void Clear();
       void Clear_str(uint8_t x, uint8_t y , uint8_t count);
       void SymbolOut(uint8_t x, uint8_t y , uint8_t symbol);
       void StringOut(uint8_t x, uint8_t y , uint8_t* string);
       void CurPos(uint8_t x, uint8_t y);
       void Sec_Print(uint32_t val);
  private:
     void Code() ;
     TQueue* queue ;

};

extern TDisplayTask* DisplayTask ;

#endif /*__DISPLAY_H__*/
