LIBNAME = libdisplay

#LIB_SRC_DIR=$(KLIBC_SRC_DIR)

include $(SRC_DIR)/rules.mk

CXXFLAGS += -I./ \
            -I$(FREERTOS_KERNEL_SRC_DIR)/include \
		    -I$(FREERTOS_PORTABLE_SRC_DIR) \
		    $(FREERTOS_DEFS) \
            $(APP_DEFS)





