ifndef PLATFORM
	PLATFORM=PLATFORM_UNKNOWN
endif

# определение микросхемы и частоты задающего кварца
ifndef CHIP
    CHIP=CHIP_UNKNOWN
endif

#тип опорного генератора OSC_TYPE :
#RCC_OSCILLATORTYPE_NONE 
#RCC_OSCILLATORTYPE_HSE - внешний высокочастотный
#RCC_OSCILLATORTYPE_HSI - внутренный высокочастотный
#RCC_OSCILLATORTYPE_LSE - внешний низкочастотный
#RCC_OSCILLATORTYPE_LSI - внутренний низкочастотный
ifndef OSC_TYPE
     OSC_TYPE = RCC_OSCILLATORTYPE_NONE
endif
#состояние опорного генератора OSC_STATE :
#RCC_HSE_OFF                      ((uint8_t)0x00)
#RCC_HSE_ON                       ((uint8_t)0x01)
#RCC_HSE_BYPASS                   ((uint8_t)0x05)
# RCC_HSE_XXX и RCC_HLE_XXX эквивалентны по значениям ( см. stm32f4xx_hal_rcc.h), поэтому используются для обоих _HSE_
ifndef OSC_STATE
     OSC_STATE = RCC_HSE_OFF
endif     
#если установлен тип RCC_OSCILLATORTYPE_HSI или RCC_OSCILLATORTYPE_LSI то RCC_HSE_BYPASS не применим


ifeq ($(PLATFORM),PLATFORM_?) # пользовательская конфигурация PLATFORM_?. параметры платформы определется в project/srс/options.mk
#	CHIP=<?>
#	F_OCS=<?>
#	OSC_TYPE=<?>
#	OSC_STATE=<?>
#	EXT_MEM_BANK0_ORIGIN=<?>
#	EXT_MEM_BANK0_SIZE=<?>
else ifeq ($(PLATFORM),OLIMEX_STM32F103RET)
	CHIP=STM32F103RET6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),OLIMEX_STM32F405RGT6_RESOLVED) # OLIMEX_STM32F103RET with resolver uC chip
	CHIP=STM32F405RGT6
	F_OCS=24000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),TE_STM32F107)
	CHIP=STM32F107VCT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),TE_STM32F405)
	CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),TE_STM32F407)
	CHIP=STM32F407VET6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),VOLKOV_STM32F405_V2)
	CHIP=STM32F405RGT6
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	ifeq ($(origin F_OCS), undefined)
        F_OCS=8000000   
        OSC_STATE=RCC_HSE_ON
	else
        OSC_STATE=RCC_HSE_BYPASS	
	endif
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=platform
else ifeq ($(PLATFORM),VODOLAZEN_M2)
	CHIP=STM32F103C8T6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),PANGEA)
	CHIP=STM32F427VIT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),PANGEA_MINI)
	CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),STM32F429_DISCOVERY)
	CHIP=STM32F429ZIT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
	# 8M sram on bank 2 (IS42S16400J)
	EXT_MEM_BANK2_ORIGIN=0xd0000000
	EXT_MEM_BANK2_SIZE=0x800000
else ifeq ($(PLATFORM),PUMP_LASER_MODULE_M0) #pump laser module revision m0
	CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),PUMP_LASER_MODULE_M1) #pump laser module revision m1
	CHIP=STM32F405RGT6
	F_OCS=12000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),LC_STUDIO)
	CHIP=STM32F103RBT6
	F_OCS=12000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),LC_STUDIO_RESOLDERING_F4)
	CHIP=STM32F415RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),LASER_MODULATOR_MODULE_M0)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),MOD01_04R1)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),SOROKIN_BLDC_V1)
    CHIP=STM32F722RET6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_BYPASS
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),MAGNITOMETR_V1)
    CHIP=STM32F405RGT6
	F_OCS=12000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),OPTO_LINK)
    CHIP=STM32F405RGT6
	F_OCS=14745600
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_BYPASS
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),OPTO_PHASE_MODULATOR)
    CHIP=STM32F405RGT6
	F_OCS=24000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),VODOLAZEN_M3)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),SOUND_MIXER_M0)
    CHIP=STM32F103RBT6
	F_OCS=12000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
#	EXT_MEM_BANK0_ORIGIN=
#	EXT_MEM_BANK0_SIZE=
else ifeq ($(PLATFORM),VOLKOV_STM32F030_V1)
    CHIP=STM32F030F4P6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSI
#	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),AMT_DEV_BOARD_V1)
    CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),PUMP_VECTOR_M0)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),BLDC_M0_DEV_BOARD)
    CHIP=STM32F415RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),SOA_MODULE_V01_01_01)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),COMMON_STM32F103_BOARD)
	CHIP=STM32F103RET6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),AMT_PANGAEA_FX)
    CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),BGESC_MINI)
        CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),SOROKIN_DEVBOARD_STM32f4_M1)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),PUMP_RX_2C)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),NUCLEO_F767ZI)
    CHIP=STM32F767ZIT6
    
    #F_OCS=16000000
	#OSC_TYPE=RCC_OSCILLATORTYPE_HSI
    
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE_BYPASS
	
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),NLL_TEST_BOARD_SET)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),MINIMUM_SYSTEM_DEV_BOARD)
    CHIP=STM32F103C8
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),NLL_M7_BOARD)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),LORA_MODEM_M1_BOARD)
    CHIP=STM32F405RGT6
	F_OCS=16000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),BALANCER_PASSSIVE_BOARD_V1)
    CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),PUMP)
    CHIP=STM32F405RGT6
    F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),TV_GENERATOR_BOARD_V1)
    CHIP=STM32F405RGT6
    F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),AMT_F7_V1A)
    CHIP=STM32F765VGT
    F_OCS=16000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),NO2)
    CHIP=STM32L011F4U
    F_OCS=16000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSI
	OSC_STATE=RCC_HSI_ON
else ifeq ($(PLATFORM),DTEC_V0)
    CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),MARCUS_ESC)
    CHIP=STM32F030x6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),EASY_MX_PRO_V7_STM32F407)
    CHIP=STM32F407VGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),NUCLEO_H743ZI)
    CHIP=STM32H743ZIT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE_BYPASS
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),NLL_V2)
    CHIP=STM32F405RGT6
	F_OCS=25000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),SYNTHESIZER_HMC832_REFBOARD)
    CHIP=STM32F405RGT6
	F_OCS=8000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON
else ifeq ($(PLATFORM),AMT_NIBIRU1)
    CHIP=STM32F765VGT
    F_OCS=12000000
	OSC_TYPE=RCC_OSCILLATORTYPE_HSE
	OSC_STATE=RCC_HSE_ON	
else
       $(error KGP BUILD SYSTEM ERROR: Platform $(PLATFORM) unknown, add platform info to /scripts/make/platform.mk)	
endif


#chip type         family      id     
#STM8
#  |
#
#STM32
#  |-----------------L1
#  |                  |--------151C8T6
#  |
#  |-----------------F0
#  |-----------------F1
#  |                  |--------103RET6
#  |                  |--------103RBT6
#  |
#  |-----------------F2
#  |-----------------F3
#  |-----------------F4
#                     |--------407VET6
#
#LPC2000
#  |


CHIP_FAMILY=CHIP_FAMILY_UNKNOWN
CPU=CPU_UNKNOWN
FLASH_SIZE=FLASH_SIZE_UNKNOWN
RAM_SIZE=RAM_SIZE_UNKNOWN
FLASH_ORIGIN=FLASH_ORIGIN_UNKNOWN
RAM_ORIGIN=RAM_ORIGIN_UNKNOWN

#определение типа микросхемы
ifneq (,$(findstring STM32,$(CHIP)))
	include $(SDK_DIR)/scripts/make/chips/stm32.mk
else ifneq (,$(findstring LPC2,$(CHIP)))
	include $(SDK_DIR)/scripts/make/chips/lpc2000.mk
else
     $(error KGP BUILD SYSTEM ERROR: Chip $(CHIP) is not valid type (stm32 or lpc2000), add type definition file to /scripts/make/platform.mk)	
endif


#DEFS=-D__$(CPU)__ -D__$(CHIP)__ -D$(CHIP_TARGET) -D__$(CHIP_FAMILY)__ $(EXT_CHIP_FAMILY_DEF) -D__$(PLATFORM)__ $(EXT_DEFS)

DEFS=-D__$(CPU)__ -D__$(CHIP)__ -D$(CHIP_TARGET) -D__$(CHIP_FAMILY)__ $(EXT_CHIP_FAMILY_DEF) -D__$(PLATFORM)__


#--------------------

