
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "DEFINE NAME COMMENTall : define all\n           | define : DEFINE NAME '(' '(' NAME '*' ')' NAME ')' define : DEFINE NAME"
    
_lr_action_items = {'NAME':([3,7,10,],[5,8,11,]),')':([9,11,],[10,12,]),'(':([5,6,],[6,7,]),'*':([8,],[9,]),'DEFINE':([0,2,5,12,],[3,3,-4,-3,]),'$end':([0,1,2,4,5,12,],[-2,0,-2,-1,-4,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'all':([0,2,],[1,4,]),'define':([0,2,],[2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> all","S'",1,None,None,None),
  ('all -> define all','all',2,'p_all','periph.py',44),
  ('all -> <empty>','all',0,'p_all','periph.py',45),
  ('define -> DEFINE NAME ( ( NAME * ) NAME )','define',9,'p_define','periph.py',48),
  ('define -> DEFINE NAME','define',2,'p_define_ignored','periph.py',53),
]
